# -*- coding: utf-8 -*-
"""ДЗ_Исключения_Уваров_Д_В.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7BxMogBc3t7jiIaNKG_gPZ80p3U9NOT

Задание 1
Печатные газеты использовали свой формат дат для каждого выпуска. Для каждой газеты из списка напишите формат указанной даты для перевода в объект datetime:
The Moscow Times - Wednesday, October 2, 2002
The Guardian - Friday, 11.10.13
Daily News - Thursday, 18 August 1977
"""

from datetime import datetime as dt1
date_The_Moscow_Times = 'Wednesday, October 2, 2002'
date_The_Guardian = 'Friday, 11.10.13'
date_Daily_News = 'Thursday, 18 August 1977'
dt_The_Moscow_Times = dt1.strptime(date_The_Moscow_Times, '%A, %B %d, %Y')
dt_The_Guardian = dt1.strptime(date_The_Guardian, '%A, %d.%m.%y')
dt_Daily_News = dt1.strptime(date_Daily_News, '%A, %d %B %Y')
print(dt_The_Moscow_Times, dt_The_Guardian, dt_Daily_News, sep = '\n')

"""Задание 2 Дан поток дат в формате YYYY-MM-DD, в которых встречаются некорректные значения:
stream = [‘2018-04-02’, ‘2018-02-29’, ‘2018-19-02’]

Напишите функцию, которая проверяет эти даты на корректность. Т. е. для каждой даты возвращает True (дата корректна) или False (некорректная дата).
"""

from datetime import datetime as dt1
stream = ['2018-04-02', '2018-02-29', '2018-19-02']
format_date = '%Y-%m-%d'
def check_date(stream,format_date):
    for date in stream:
        try:
            dt1.strptime(date, format_date)
            print(date, 'дата корректна')
        except:
            print(date, 'некорректная дата')
check_date(stream,format_date)

"""Задание 3 Напишите функцию date_range, которая возвращает список дат за период от start_date до end_date. Даты должны вводиться в формате YYYY-MM-DD. В случае неверного формата или при start_date > end_date должен возвращаться пустой список."""

from datetime import timedelta as td1
from datetime import datetime as dt1
start_date = '2018-01-01'
end_date = '2018-02-07'
def date_range(start_date, end_date):
    current_dt_list = []
    try:
        start_date_dt = dt1.strptime(start_date, '%Y-%m-%d')
        end_date_dt = dt1.strptime(end_date, '%Y-%m-%d')
        current_dt = start_date_dt
        while current_dt <= end_date_dt:
            current_dt_list.append(current_dt.strftime('%Y-%m-%d'))
            current_dt += td1(days=1)
    except:
        print('некорректная дата')
    print(current_dt_list)
date_range(start_date, end_date)

DEFAULT_USER_COUNT = 3

def delete_and_return_last_user(region, default_list=['A100', 'A101', 'A102']):
   element_to_delete = default_list[-1]
   default_list.remove(element_to_delete)

default_list=['A100', 'A101', 'A102']
element_to_delete = default_list[-1]
default_list.remove(element_to_delete)
default_list[DEFAULT_USER_COUNT-2]
element_to_delete = default_list[-1]
default_list.remove(element_to_delete)
default_list[-1]

"""1. Что значит ошибка list index out of range? - Элемента списка с указанным индексом не существует.

2. Почему при первом запуске функция работает корректно, а при втором - нет?
При первом запуске элементы списка имеют следующие значения:

А102 - default_list[-1]

А101 - default_list[-2]

А100 - default_list[-3]

После первого выполнения

А101 - default_list[-1]

А100 - default_list[-2]

Во время второго выполнения

element_to_delete = default_list[-1]

default_list.remove(element_to_delete)

А100 - default_list[-1], т.е. default_list[-2] - не существует.
"""